export const SETTLEMENT = {
    //SETTLEMENT
    SETTLEMENT_STATUS_UNSETTLED: 0,
    SETTLEMENT_STATUS_APPROVAL_ERROR: 1,
    SETTLEMENT_STATUS_APPROVED: 2,
    SETTLEMENT_STATUS_CAPTURE_ERROR: 3,
    SETTLEMENT_STATUS_CAPTURED: 4,
    SETTLEMENT_STATUS_VOID_ERROR: 5,
    SETTLEMENT_STATUS_VOIDED: 6,
    
    SETTLEMENT_LABELS: ['', 'オーソリエラー', '売上処理未済', '売上処理エラー', '売上処理済み', 'キャンセルエラー', 'キャンセル済み'],
};

export const BUSINESS_CARD = {
    BUSINESS_CARDS_EXPIRED_LABELS: ['契約中', '期限切れ'],
};
