-- MySQL Script generated by MySQL Workbench
-- Wed May 20 17:22:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opniddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opniddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opniddb` DEFAULT CHARACTER SET utf8mb4 ;
USE `opniddb` ;

-- -----------------------------------------------------
-- Table `opniddb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`users` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`users` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(255) NULL DEFAULT NULL,
  `qr_i_token` CHAR(36) NOT NULL,
  `qr_g_token` CHAR(44) NOT NULL,
  `is_authenticated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not authenticated, 1: authenticated',
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not archived, 1: archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `qr_g_token_UNIQUE` (`qr_g_token` ASC) VISIBLE,
  UNIQUE INDEX `qr_i_token_UNIQUE` (`qr_i_token` ASC) VISIBLE,
  INDEX `users_email_idx` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`prefectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`prefectures` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`prefectures` (
  `prefecture_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`prefecture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`companies` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`companies` (
  `company_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `str_customer_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name_for_index` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT 'Character string obtained by removing \"株式会社\" from the company name.',
  `name_en` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` CHAR(8) NULL DEFAULT NULL,
  `prefecture_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `subsequent_address` VARCHAR(255) NULL DEFAULT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not archived, 1: archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `fk_companies_prefectures1_idx` (`prefecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_prefectures1`
    FOREIGN KEY (`prefecture_id`)
    REFERENCES `opniddb`.`prefectures` (`prefecture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`departments` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`departments` (
  `department_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `fk_departments_companies1_idx` (`company_id` ASC) VISIBLE,
  INDEX `departments_name_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_departments_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`positions` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`positions` (
  `position_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`position_id`),
  INDEX `fk_positions_companies1_idx` (`company_id` ASC) VISIBLE,
  INDEX `positions_name_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_positions_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`business_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`business_cards` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`business_cards` (
  `business_card_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `str_subscription_id` VARCHAR(255) NULL DEFAULT NULL,
  `str_subscription_sched_id` VARCHAR(255) NULL DEFAULT NULL,
  `setting_code` CHAR(29) NOT NULL,
  `last_name_kanji` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `first_name_kanji` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `name_kanji_for_index` VARCHAR(255) NOT NULL COMMENT 'last_name_kanji + first_name_kanji',
  `last_name_kana` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `first_name_kana` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `name_kana_for_index` VARCHAR(255) NULL DEFAULT NULL COMMENT 'last_name_kana + first_name_kana',
  `department_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `position_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `employee_number` VARCHAR(255) NULL DEFAULT NULL,
  `hire_date` DATE NULL DEFAULT NULL,
  `email` VARCHAR(254) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `display_order` INT(11) UNSIGNED NOT NULL,
  `is_expired` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not expired, 1: expired',
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not archived, 1: archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`business_card_id`),
  INDEX `fk_business_cards_companies1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_business_cards_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `setting_code_UNIQUE` (`setting_code` ASC) VISIBLE,
  INDEX `fk_business_cards_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_business_cards_positions1_idx` (`position_id` ASC) VISIBLE,
  INDEX `business_cards_name_kanji_for_index_idx` (`name_kanji_for_index` ASC) VISIBLE,
  INDEX `business_cards_name_kana_for_index_idx` (`name_kana_for_index` ASC) VISIBLE,
  INDEX `business_cards_str_subscription_id_idx` (`str_subscription_id` ASC) VISIBLE,
  CONSTRAINT `fk_business_cards_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_cards_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opniddb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_cards_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `opniddb`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_cards_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `opniddb`.`positions` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`image_paths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`image_paths` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`image_paths` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `business_card_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `file_name` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”000000000061568564639.png\"',
  `dir_path` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”companies/6/profiles/\"',
  `image_url` VARCHAR(255) NOT NULL COMMENT 'Ex.) \"https://s3-appname-jp.s3.ap-northeast-1.amazonaws.com/companies/6/profiles/000000000061568564639.png\"',
  `display_order` TINYINT(2) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_paths_companies1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_image_paths_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_paths_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_paths_business_cards1`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`password_resets` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(2) NOT NULL COMMENT '1: general user, 2:admin user, 3: management portal user (OPD admin user)',
  `email` VARCHAR(254) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `password_resets_email_idx` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`management_portal_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`management_portal_users` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`management_portal_users` (
  `management_portal_user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(255) NULL DEFAULT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not archived, 1: archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`management_portal_user_id`),
  INDEX `management_portal_users_email_idx` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`plans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`plans` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`plans` (
  `plan_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(15,0) NOT NULL,
  `contract_period` TINYINT(2) NOT NULL COMMENT 'Ex.) 1: 1 month, 3: 3 months, 12: 12 months',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`email_authns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`email_authns` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`email_authns` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(2) NOT NULL COMMENT '1: general user, 2:admin user, 3: management portal user (OPD admin user)',
  `email` VARCHAR(254) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `email_authns_email_idx` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`additional_company_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`additional_company_profiles` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`additional_company_profiles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NOT NULL,
  `item_title` VARCHAR(255) NOT NULL,
  `item_body` TEXT NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_additional_company_profiles_companies1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_additional_company_profiles_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`additional_business_card_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`additional_business_card_profiles` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`additional_business_card_profiles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `item_title` VARCHAR(255) NOT NULL,
  `item_body` TEXT NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_additional_business_card_profiles_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_additional_business_card_profiles_business_cards1`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`business_card_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`business_card_groups` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`business_card_groups` (
  `business_card_id_grouping` INT(11) UNSIGNED NOT NULL,
  `business_card_id_grouped` INT(11) UNSIGNED NOT NULL,
  `display_order` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `fk_business_card_groups_business_cards1_idx` (`business_card_id_grouping` ASC) VISIBLE,
  INDEX `fk_business_card_groups_business_cards2_idx` (`business_card_id_grouped` ASC) VISIBLE,
  PRIMARY KEY (`business_card_id_grouping`, `business_card_id_grouped`),
  CONSTRAINT `fk_business_card_groups_business_cards1`
    FOREIGN KEY (`business_card_id_grouping`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_card_groups_business_cards2`
    FOREIGN KEY (`business_card_id_grouped`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`contracts` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`contracts` (
  `contract_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_id` INT(11) UNSIGNED NOT NULL,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `settlement_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: unsettled, 1: approval error, 2: approved 3: capture error, 4: captured(completed), 5: void error, 6: voided(canceled)',
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `price` DECIMAL(15,0) NOT NULL,
  `cancellation_reservation_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not reserved, 1: reserved',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `fk_contracts_plans1_idx` (`plan_id` ASC) VISIBLE,
  INDEX `fk_contracts_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_plans1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `opniddb`.`plans` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contracts_business_cards1`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`settlements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`settlements` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`settlements` (
  `settlement_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `str_payment_id` VARCHAR(255) NULL DEFAULT NULL,
  `contract_id` BIGINT(20) UNSIGNED NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'JPY',
  `status` TINYINT(1) NOT NULL COMMENT '1: approval error, 2: approved 3: capture error, 4: captured(completed), 5: void error, 6: voided(canceled)',
  `approval_error_reason` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Set ERROR TYPE value of Stripe like “card_error”.',
  `approval_failed_at` TIMESTAMP NULL DEFAULT NULL,
  `approved_amount` DECIMAL(15,0) NULL DEFAULT NULL,
  `approved_at` TIMESTAMP NULL DEFAULT NULL,
  `capture_error_reason` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Set ERROR TYPE value of Stripe like “card_error”.',
  `capture_failed_at` TIMESTAMP NULL DEFAULT NULL,
  `captured_amount` DECIMAL(15,0) NULL DEFAULT NULL,
  `captured_at` TIMESTAMP NULL DEFAULT NULL,
  `cancellation_error_reason` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Set ERROR TYPE value of Stripe like “card_error”.',
  `cancellation_failed_at` TIMESTAMP NULL DEFAULT NULL,
  `canceled_amount` DECIMAL(15,0) NULL DEFAULT NULL,
  `canceled_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`settlement_id`),
  INDEX `fk_settlements_contracts1_idx` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_settlements_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `opniddb`.`contracts` (`contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`company_admin_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`company_admin_users` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`company_admin_users` (
  `company_admin_user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) UNSIGNED NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(255) NULL DEFAULT NULL,
  `is_authenticated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not authenticated, 1: authenticated',
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not archived, 1: archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`company_admin_user_id`),
  INDEX `fk_company_admin_users_companies1_idx` (`company_id` ASC) VISIBLE,
  INDEX `company_admin_users_email_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_company_admin_users_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `opniddb`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`inquiries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`inquiries` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`inquiries` (
  `inquiry_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `inquiry_type` TINYINT(1) NOT NULL,
  `body` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`inquiry_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`received_business_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`received_business_cards` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`received_business_cards` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `received_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `fk_received_business_cards_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_received_business_cards_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `business_card_id`),
  CONSTRAINT `fk_received_business_cards_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opniddb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_received_business_cards_business_cards1`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`receipt_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`receipt_histories` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`receipt_histories` (
  `receipt_history_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receiving_user_id` INT(11) UNSIGNED NOT NULL,
  `received_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`receipt_history_id`),
  INDEX `fk_receipt_histories_users1_idx` (`receiving_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_histories_users1`
    FOREIGN KEY (`receiving_user_id`)
    REFERENCES `opniddb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`receipt_history_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`receipt_history_details` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`receipt_history_details` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receipt_history_id` INT(11) UNSIGNED NOT NULL,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_a` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receipt_history_details_receipt_histories1_idx` (`receipt_history_id` ASC) VISIBLE,
  INDEX `fk_receipt_history_details_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_history_details_receipt_histories1`
    FOREIGN KEY (`receipt_history_id`)
    REFERENCES `opniddb`.`receipt_histories` (`receipt_history_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_history_details_business_cards1`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`temporary_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`temporary_users` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`temporary_users` (
  `temporary_user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(255) NOT NULL,
  `is_data_migrated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: not migrated, 1: migrated',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`temporary_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`temporarily_received_business_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`temporarily_received_business_cards` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`temporarily_received_business_cards` (
  `temporary_user_id` BIGINT(20) UNSIGNED NOT NULL,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `received_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `fk_received_business_cards_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  PRIMARY KEY (`temporary_user_id`, `business_card_id`),
  INDEX `fk_temporarily_received_business_cards_temporary_users1_idx` (`temporary_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_received_business_cards_business_cards10`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temporarily_received_business_cards_temporary_users1`
    FOREIGN KEY (`temporary_user_id`)
    REFERENCES `opniddb`.`temporary_users` (`temporary_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`temporary_receipt_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`temporary_receipt_histories` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`temporary_receipt_histories` (
  `temporary_receipt_history_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `temporary_user_id` BIGINT(20) UNSIGNED NOT NULL,
  `received_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`temporary_receipt_history_id`),
  INDEX `fk_temporary_receipt_histories_temporary_users1_idx` (`temporary_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_temporary_receipt_histories_temporary_users1`
    FOREIGN KEY (`temporary_user_id`)
    REFERENCES `opniddb`.`temporary_users` (`temporary_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opniddb`.`temporary_receipt_history_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opniddb`.`temporary_receipt_history_details` ;

CREATE TABLE IF NOT EXISTS `opniddb`.`temporary_receipt_history_details` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `temporary_receipt_history_id` INT(11) UNSIGNED NOT NULL,
  `business_card_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receipt_history_details_business_cards1_idx` (`business_card_id` ASC) VISIBLE,
  INDEX `fk_temporary_receipt_history_details_temporary_receipt_hist_idx` (`temporary_receipt_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_history_details_business_cards10`
    FOREIGN KEY (`business_card_id`)
    REFERENCES `opniddb`.`business_cards` (`business_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temporary_receipt_history_details_temporary_receipt_histor1`
    FOREIGN KEY (`temporary_receipt_history_id`)
    REFERENCES `opniddb`.`temporary_receipt_histories` (`temporary_receipt_history_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `opniddb`.`prefectures`
-- -----------------------------------------------------
START TRANSACTION;
USE `opniddb`;
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (1, '北海道', 1, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (2, '青森県', 2, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (3, '岩手県', 3, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (4, '宮城県', 4, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (5, '秋田県', 5, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (6, '山形県', 6, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (7, '福島県', 7, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (8, '茨城県', 8, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (9, '栃木県', 9, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (10, '群馬県', 10, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (11, '埼玉県', 11, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (12, '千葉県', 12, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (13, '東京都', 13, 1, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (14, '神奈川県', 14, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (15, '新潟県', 15, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (16, '富山県', 16, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (17, '石川県', 17, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (18, '福井県', 18, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (19, '山梨県', 19, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (20, '長野県', 20, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (21, '岐阜県', 21, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (22, '静岡県', 22, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (23, '愛知県', 23, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (24, '三重県', 24, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (25, '滋賀県', 25, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (26, '京都府', 26, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (27, '大阪府', 27, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (28, '兵庫県', 28, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (29, '奈良県', 29, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (30, '和歌山県', 30, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (31, '鳥取県', 31, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (32, '島根県', 32, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (33, '岡山県', 33, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (34, '広島県', 34, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (35, '山口県', 35, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (36, '徳島県', 36, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (37, '香川県', 37, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (38, '愛媛県', 38, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (39, '高知県', 39, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (40, '福岡県', 40, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (41, '佐賀県', 41, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (42, '長崎県', 42, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (43, '熊本県', 43, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (44, '大分県', 44, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (45, '宮崎県', 45, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (46, '鹿児島県', 46, 0, '2019-10-15 18:10', '2019-10-15 18:10');
INSERT INTO `opniddb`.`prefectures` (`prefecture_id`, `name`, `display_order`, `is_default`, `created_at`, `updated_at`) VALUES (47, '沖縄県', 47, 0, '2019-10-15 18:10', '2019-10-15 18:10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `opniddb`.`plans`
-- -----------------------------------------------------
START TRANSACTION;
USE `opniddb`;
INSERT INTO `opniddb`.`plans` (`plan_id`, `name`, `price`, `contract_period`, `created_at`, `updated_at`) VALUES (1, '月契約', 240, 1, '2020-03-28 22:30:00', '2020-03-28 22:30:00');
INSERT INTO `opniddb`.`plans` (`plan_id`, `name`, `price`, `contract_period`, `created_at`, `updated_at`) VALUES (2, '年契約', 2000, 12, '2020-03-28 22:30:00', '2020-03-28 22:30:00');

COMMIT;

