// Auth
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const FETCH_AUTH = 'FETCH_AUTH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_RESET = 'AUTH_FORGOT_PASSWORD_RESET';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_CONFIRM_REGISTER_SUCCESS = 'AUTH_CONFIRM_REGISTER_SUCCESS';
export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const COMPANY_USER_ADMIN = 'COMPANY_USER_ADMIN';
export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST';
export const GET_USER_AUTH_BY_ID = 'GET_USER_AUTH_BY_ID';
